package:
  name: udunits2
  version: 2.1.24
source:
  fn:  udunits-2.1.24.tar.gz
  url: ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.1.24.tar.gz
  md5: 6986545721747a51285c765644dcd9d8

build:
  number: 0

requirements:
  build:

  run:

test:
  imports:

  commands:

about:
  home: http://www.unidata.ucar.edu
  license: 
