run_ids:
    - "NG_5120x2560x34_4km_10s_QOBS_EQX"
    - "NG_5120x2560x34_4km_10s_QOBS_EQX_4K"
output_dir: "/home/disk/eos4/nbren12/eos8/Data/id/2"
dataroot: "/home/disk/eos17/guest/SAM6.10.6_NG"
fields_2d:
    - "Prec"
    - "SHF"
    - "LHF"
    - "LWNS"
    - "LWNSC"
    - "LWNT"
    - "LWNTC"
    - "SOLIN"
    - "SWNS"
    - "SWNSC"
    - "SWNT"
    - "SWNTC"
    - "CWP"
    - "IWP"
    - "CLD"
    - "PW"
    - "TA"
    - "USFC"
    - "U200"
    - "VSFC"
    - "V200"
    - "W500"
    - "SST"
    - "PSFC"
    - "SWVP"
    - "U850"
    - "V850"
    - "ZC"
    - "TB"
    - "ZE"
    - "CLDC"
